version: '3.9'

networks:
  projectmanagementservice-network:
    driver: bridge

volumes:
  postgresdbdata:

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - projectmanagementservice-network
      
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdbdata:/var/lib/postgresql/data
    networks:
      - projectmanagementservice-network
      
  identitymanagementservice:
    container_name: identitymanagementservice
    image: ${DOCKER_REGISTRY-}identitymanagementservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./IdentityManagementService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - postgres
    networks:
      - projectmanagementservice-network
    command: ["dotnet", "ef", "database", "update"]
      
  projectmanagementservice:
    container_name: projectmanagementservice
    image: ${DOCKER_REGISTRY-}projectmanagementservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./ProjectManagementService
      dockerfile: Dockerfile
    ports:
      - "5012:80"
    depends_on:
      - postgres
    networks:
      - projectmanagementservice-network
    command: ["dotnet", "ef", "database", "update"]
      
  meetingservice:
    container_name: meetingservice
    image: ${DOCKER_REGISTRY-}meetingservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: ./MeetingService
      dockerfile: Dockerfile
    ports:
      - "5102:80"
    depends_on:
      - redis
    networks:
      - projectmanagementservice-network
      
#   client:
#    container_name: client
#    build:
#      context: ./Client
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    networks:
#      - projectmanagementservice-network
#    depends_on:
#      - identitymanagementservice
#      - projectmanagementservice
#      - meetingservice