version: '3.9'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
      
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      
  projectmanagementservice:
    image: ${DOCKER_REGISTRY-}projectmanagementservice
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
    build:
      context: ./ProjectManagementService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres
    command: ["dotnet", "ef", "database", "update"]
      
  identitymanagementservice:
    image: ${DOCKER_REGISTRY-}identitymanagementservice
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
    build:
      context: ./IdentityManagementService
      dockerfile: Dockerfile
    ports:
      - "5011:81"
    depends_on:
      - postgres
    command: ["dotnet", "ef", "database", "update"]
      
  meetingservice:
    image: ${DOCKER_REGISTRY-}meetingservice
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
    build:
      context: ./MeetingService
      dockerfile: Dockerfile
    ports:
      - "5101:82"
    depends_on:
      - redis
      
#   client:
#    build:
#      context: Client/
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#      - identitymanagementservice
#      - projectmanagementservice
#      - meetingservice